version: 2

project_name: mongo-lock

release:
  github:
    owner: foomo
    name: mongo-lock
  prerelease: auto

builds:
  - skip: true

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

changelog:
  use: github-native
